id: I97AA79E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T05:15:25+00:00'
last_modified: '2022-06-07T20:23:36.190313+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ881
  title: ལི་ཐང་བཀའ་འགྱུར་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    645C:
      image_group_id: I1CZ2117
      title: ''
      total_pages: 137
      order: 1
      base_file: 645C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
