id: I97AA79E4
legacy_id: P003316
ocr_import_info:
  bdrc_scan_id: W1CZ881
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T05:14:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:38:36.783468+00:00'
last_modified: 2022-08-31 03:38:51.068060
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ881
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ881
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལི་ཐང་བཀའ་འགྱུར་དཀར་ཆག
  author: ཞྭ་དམར ༠༦་ཆོས་ཀྱི་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.3923866134376552
  ocr_word_median_confidence_index: 0.3100000023841858
quality: null
bases:
  I1CZ2117:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2117
      total_pages: 137
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2117.txt
    statistics:
      ocr_word_median_confidence_index: 0.3100000023841858
      ocr_word_mean_confidence_index: 0.3923866134376552
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
