id: P003316
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ881
  title: ལི་ཐང་བཀའ་འགྱུར་དཀར་ཆག
  author: ''
  volumes:
    1ceaf2fb8d6b4bdcb735d19d21ebe3db:
      image_group_id: I1CZ2117
      title: ''
      volume_number: 1
      total_pages: 137
      base_file: v001.txt
